microservices:
  receipt:
    url: http://receipt-service.prod.eciexpress.com
  promotion:
    url: http://promotion-service.prod.eciexpress.com
  wallet:
    url: http://wallet-service.prod.eciexpress.com
  base-url: https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi
  api-login: pRRXKOl8ikMmt9u
  api-key: 4Vj8eK4rloUd272L48hsrarnUA